import 'dotenv/config';
import express from 'express'; import cors from 'cors'; import path from 'node:path';
import { initializeDatabase } from './config/database.js'; import auth from './routes/auth.js'; import complaints from './routes/complaints.js'; import reports from './routes/reports.js'; import departments from './routes/departments.js'; import admin from './routes/admin.js'; import notifications from './routes/notifications.js'; import dashboard from './routes/dashboard.js';
initializeDatabase();
export const app=express();
const origins=(process.env.ALLOWED_ORIGINS||'http://localhost:3000,http://localhost:5173,http://localhost:8080').split(',').map(s=>s.trim()).filter(Boolean);
app.use(cors({origin:origins,credentials:true}));app.use(express.json({limit:'2mb'}));app.use('/uploads',express.static(path.resolve(process.cwd(),'uploads')));
app.get('/health',(_req,res)=>res.json({status:'ok',service:'u-connect-backend',time:new Date().toISOString()}));
app.use('/api/auth',auth);app.use('/api/complaints',complaints);app.use('/api/reports',reports);app.use('/api/departments',departments);app.use('/api/admin',admin);app.use('/api/notifications',notifications);app.use('/api/dashboard',dashboard);
app.use((_req,res)=>res.status(404).json({error:'Endpoint not found'}));
app.use((err:any,_req:any,res:any,_next:any)=>{console.error(err);res.status(500).json({error:'Internal server error'});});
