import PDFDocument from 'pdfkit';
import { Complaint } from '../models/types';
import type { ComplaintFilterDTO } from '../services/complaint.service';

export function generateComplaintsPdf(
  complaints: Complaint[],
  _filters?: ComplaintFilterDTO
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        layout: 'landscape',
        size: 'A4',
        margin: 25,
        bufferPages: true,
      });

      const buffers: Buffer[] = [];
      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', (err) => reject(err));

      const pageWidth = 841.89;
      const pageHeight = 595.28;
      const margin = 25;
      const contentWidth = pageWidth - margin * 2; // 791.89

      // Calculate Summary Metrics
      const total = complaints.length;
      const pendingCount = complaints.filter((c) => c.status === 'pending').length;
      const inProgressCount = complaints.filter((c) => c.status === 'in-progress').length;
      const resolvedCount = complaints.filter((c) => c.status === 'resolved').length;
      const closedCount = complaints.filter((c) => c.status === 'closed').length;
      const slaEscalatedCount = complaints.filter((c) => c.sla_escalated).length;

      // Draw Header Banner
      const drawHeader = () => {
        doc.save();
        doc.rect(margin, margin, contentWidth, 48).fill('#0f172a');
        doc.fillColor('#ffffff').fontSize(14).font('Helvetica-Bold');
        doc.text('U-CONNECT INSTITUTIONAL GRIEVANCE MANAGEMENT SYSTEM', margin + 14, margin + 10);
        doc.fillColor('#94a3b8').fontSize(8.5).font('Helvetica');
        const formattedDate = new Date().toLocaleString('en-GB', {
          day: 'numeric',
          month: 'short',
          year: 'numeric',
          hour: '2-digit',
          minute: '2-digit',
        });
        doc.text(
          `Official Audit Dataset | Generated by Administrator on ${formattedDate} | Confidential`,
          margin + 14,
          margin + 28
        );
        doc.restore();
      };

      drawHeader();

      let currentY = margin + 58;

      // Summary KPIs Box
      const kpis = [
        { label: 'TOTAL COMPLAINTS', value: total, color: '#0f172a', bg: '#f1f5f9' },
        { label: 'PENDING TRIAGE', value: pendingCount, color: '#b45309', bg: '#fef3c7' },
        { label: 'IN PROGRESS', value: inProgressCount, color: '#0369a1', bg: '#e0f2fe' },
        { label: 'RESOLVED CASES', value: resolvedCount, color: '#15803d', bg: '#dcfce7' },
        { label: 'TERMINAL CLOSED', value: closedCount, color: '#475569', bg: '#f1f5f9' },
        { label: 'SLA ESCALATED', value: slaEscalatedCount, color: '#b91c1c', bg: '#fee2e2' },
      ];

      const kpiWidth = (contentWidth - (kpis.length - 1) * 8) / kpis.length;
      kpis.forEach((kpi, index) => {
        const x = margin + index * (kpiWidth + 8);
        doc.save();
        doc.rect(x, currentY, kpiWidth, 36).fill(kpi.bg);
        doc.rect(x, currentY, kpiWidth, 36).strokeColor('#cbd5e1').lineWidth(0.5).stroke();
        doc.fillColor(kpi.color).fontSize(14).font('Helvetica-Bold');
        doc.text(String(kpi.value), x + 8, currentY + 6);
        doc.fillColor(kpi.color).fontSize(6.5).font('Helvetica-Bold');
        doc.text(kpi.label, x + 8, currentY + 23);
        doc.restore();
      });

      currentY += 46;

      // Columns configuration
      const columns = [
        { key: 'ref', title: 'REF NO', width: 72 },
        { key: 'title', title: 'GRIEVANCE TITLE', width: 170 },
        { key: 'category', title: 'CATEGORY', width: 80 },
        { key: 'department', title: 'DEPARTMENT', width: 110 },
        { key: 'priority', title: 'PRIORITY', width: 62 },
        { key: 'status', title: 'STATUS', width: 75 },
        { key: 'user', title: 'COMPLAINANT', width: 95 },
        { key: 'evidence', title: 'EVIDENCE', width: 58 },
        { key: 'date', title: 'SUBMITTED', width: 70 },
      ];

      const drawTableHeader = (y: number) => {
        doc.save();
        doc.rect(margin, y, contentWidth, 20).fill('#1e293b');
        let colX = margin + 6;
        doc.fillColor('#ffffff').fontSize(7.5).font('Helvetica-Bold');
        columns.forEach((col) => {
          doc.text(col.title, colX, y + 6, { width: col.width - 6, ellipsis: true });
          colX += col.width;
        });
        doc.restore();
      };

      drawTableHeader(currentY);
      currentY += 20;

      const rowHeight = 20;
      const maxY = pageHeight - margin - 25;

      complaints.forEach((c, index) => {
        // If bottom reached, add new page
        if (currentY + rowHeight > maxY) {
          doc.addPage({ layout: 'landscape', size: 'A4', margin: 25 });
          drawHeader();
          currentY = margin + 58;
          drawTableHeader(currentY);
          currentY += 20;
        }

        const isEven = index % 2 === 0;
        doc.save();
        if (isEven) {
          doc.rect(margin, currentY, contentWidth, rowHeight).fill('#f8fafc');
        } else {
          doc.rect(margin, currentY, contentWidth, rowHeight).fill('#ffffff');
        }
        doc.rect(margin, currentY, contentWidth, rowHeight).strokeColor('#e2e8f0').lineWidth(0.5).stroke();

        let colX = margin + 6;
        const refNo = `UC-2025-${c.id.toString().padStart(3, '0')}`;
        const deptName = c.department?.name || 'Unassigned';
        const complainant = c.anonymous
          ? 'Anonymous'
          : c.user?.name || (c.user_id ? `Student #${c.user_id}` : 'Student');
        const evidenceText = c.attachments && c.attachments.length > 0 ? `${c.attachments.length} file(s)` : 'None';
        const formattedDate = new Date(c.created_at).toLocaleDateString('en-GB', {
          day: 'numeric',
          month: 'short',
          year: 'numeric',
        });

        // Ref
        doc.fillColor('#2563eb').fontSize(7.5).font('Helvetica-Bold');
        doc.text(refNo, colX, currentY + 6, { width: columns[0].width - 6, ellipsis: true });
        colX += columns[0].width;

        // Title
        doc.fillColor('#0f172a').fontSize(7.5).font('Helvetica');
        doc.text(c.title, colX, currentY + 6, { width: columns[1].width - 6, ellipsis: true });
        colX += columns[1].width;

        // Category
        doc.fillColor('#475569').fontSize(7.5).font('Helvetica');
        doc.text(String(c.category), colX, currentY + 6, { width: columns[2].width - 6, ellipsis: true });
        colX += columns[2].width;

        // Department
        doc.fillColor('#475569').fontSize(7.5).font('Helvetica');
        doc.text(deptName, colX, currentY + 6, { width: columns[3].width - 6, ellipsis: true });
        colX += columns[3].width;

        // Priority
        const priorityColors: Record<string, string> = {
          critical: '#b91c1c',
          high: '#c2410c',
          medium: '#1d4ed8',
          low: '#64748b',
        };
        doc.fillColor(priorityColors[c.priority] || '#475569').fontSize(7.5).font('Helvetica-Bold');
        doc.text(c.priority.toUpperCase(), colX, currentY + 6, { width: columns[4].width - 6, ellipsis: true });
        colX += columns[4].width;

        // Status
        const statusColors: Record<string, string> = {
          pending: '#b45309',
          'in-progress': '#0369a1',
          resolved: '#15803d',
          closed: '#64748b',
        };
        doc.fillColor(statusColors[c.status] || '#475569').fontSize(7.5).font('Helvetica-Bold');
        doc.text(c.status.toUpperCase(), colX, currentY + 6, { width: columns[5].width - 6, ellipsis: true });
        colX += columns[5].width;

        // Complainant
        doc.fillColor('#334155').fontSize(7.5).font('Helvetica');
        doc.text(complainant, colX, currentY + 6, { width: columns[6].width - 6, ellipsis: true });
        colX += columns[6].width;

        // Evidence
        doc.fillColor(c.attachments && c.attachments.length > 0 ? '#2563eb' : '#94a3b8').fontSize(7.5).font('Helvetica');
        doc.text(evidenceText, colX, currentY + 6, { width: columns[7].width - 6, ellipsis: true });
        colX += columns[7].width;

        // Date
        doc.fillColor('#64748b').fontSize(7.5).font('Helvetica');
        doc.text(formattedDate, colX, currentY + 6, { width: columns[8].width - 6, ellipsis: true });

        doc.restore();
        currentY += rowHeight;
      });

      // Footer with page numbering on all pages
      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);
        doc.save();
        const footerY = pageHeight - margin + 8;
        doc.strokeColor('#e2e8f0').lineWidth(0.5);
        doc.moveTo(margin, footerY - 5).lineTo(margin + contentWidth, footerY - 5).stroke();

        doc.fillColor('#94a3b8').fontSize(7).font('Helvetica');
        doc.text(
          'Confidential Institutional Record — University Grievance Audit & Oversight Committee',
          margin,
          footerY
        );
        doc.text(`Page ${i + 1} of ${range.count}`, margin + contentWidth - 80, footerY, {
          width: 80,
          align: 'right',
        });
        doc.restore();
      }

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}
