import { Router } from 'express'; import multer from 'multer'; import fs from 'node:fs'; import path from 'node:path';
import { db, nowIso } from '../config/database.js'; import { authenticate, requireRole } from '../middleware/auth.js'; import { fail, ok } from '../utils/response.js'; import { audit } from '../services/audit.js'; import { complaintSchema, complaintUpdateSchema, statusSchema, assignSchema, commentSchema, feedbackSchema } from '../validators/schemas.js';
const router=Router();router.use(authenticate);const uploadDir=path.resolve(process.cwd(),'uploads');fs.mkdirSync(uploadDir,{recursive:true});const upload=multer({dest:uploadDir,limits:{fileSize:10*1024*1024}});
const select=`SELECT c.*, u.id user_id,u.name user_name,u.username user_username,u.email user_email,u.role user_role,d.id department_id,d.name department_name,d.code department_code FROM complaints c JOIN users u ON u.id=c.user_id JOIN departments d ON d.id=c.department_id`;
export function shape(r:any){return {...r,id:r.id,reference_number:r.reference_number,title:r.title,description:r.description,category:r.category,location:r.location,priority:r.priority,status:r.status,anonymous:!!r.anonymous,sla_escalated:!!r.sla_escalated,user_id:r.user_id,user:r.anonymous?null:{id:r.user_id,name:r.user_name,username:r.user_username,email:r.user_email,role:r.user_role},department:{id:r.department_id,name:r.department_name,code:r.department_code},resolved_at:r.resolved_at,created_at:r.created_at,updated_at:r.updated_at};}
function getComplaint(id:number){return db.prepare(select+' WHERE c.id=?').get(id) as any;}
function allowed(req:any,c:any){return req.user.role!=='student'||c.user_id===req.user.user_id;}
function priority(desc:string,category:string){const d=desc.toLowerCase();if(['emergency','urgent','critical','immediate','danger'].some(k=>d.includes(k)))return 'critical';if(category==='Exam Hall'||category==='Safety')return 'high';return 'medium';}
router.post('/',(req,res)=>{const p=complaintSchema.safeParse(req.body);if(!p.success)return fail(res,400,'Invalid complaint payload');const category=db.prepare('SELECT category_id FROM categories WHERE category_name=? AND is_active=1').get(p.data.category);if(!category)return fail(res,400,'Invalid category');const dept=db.prepare('SELECT id FROM departments WHERE id=?').get(req.body.department_id);if(!dept)return fail(res,400,'Department not found');const t=nowIso();try{db.exec('BEGIN');const r=db.prepare(`INSERT INTO complaints(reference_number,title,description,category,location,priority,status,anonymous,sla_escalated,user_id,department_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).run('TEMP',p.data.title,p.data.description,p.data.category,p.data.location,priority(p.data.description,p.data.category),'pending',p.data.anonymous?1:0,0,req.user!.user_id,req.body.department_id,t,t);const id=Number(r.lastInsertRowid),ref=`UC-${id.toString().padStart(6,'0')}`;db.prepare('UPDATE complaints SET reference_number=? WHERE id=?').run(ref,id);db.prepare('INSERT INTO complaint_updates(complaint_id,user_id,status,comment,updated_at) VALUES (?,?,?,?,?)').run(id,req.user!.user_id,'pending','Complaint submitted',t);db.prepare('INSERT INTO notifications(user_id,type,title,description,related_complaint_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').run(req.user!.user_id,'complaint','Complaint submitted',`Your complaint "${p.data.title}" was submitted successfully.`,id,t,t);audit(req.user!.user_id,'CREATE','complaints',id);db.exec('COMMIT');const c=getComplaint(id);return ok(res,shape(c),'Complaint submitted');}catch(error){try{db.exec('ROLLBACK');}catch{}return fail(res,500,'Failed to submit complaint');}});
router.get('/',(req,res)=>{const q=req.query;const page=Math.max(1,Number(q.page)||1),pageSize=Math.min(100,Math.max(1,Number(q.page_size)||20));const cond:string[]=[];const args:any[]=[];if(req.user!.role==='student'){cond.push('c.user_id=?');args.push(req.user!.user_id)}if(q.reference_number){cond.push('c.reference_number=?');args.push(String(q.reference_number))}if(q.status){cond.push('c.status=?');args.push(String(q.status))}if(q.category){cond.push('c.category=?');args.push(String(q.category))}if(q.priority){cond.push('c.priority=?');args.push(String(q.priority))}if(q.department_id){cond.push('c.department_id=?');args.push(Number(q.department_id))}if(q.sla_escalated!==undefined){cond.push('c.sla_escalated=?');args.push(String(q.sla_escalated)==='true'?1:0)}const where=cond.length?' WHERE '+cond.join(' AND '):'';const total=Number((db.prepare(`SELECT count(*) c FROM complaints c${where}`).get(...args) as any).c);const rows=db.prepare(`${select}${where} ORDER BY c.created_at DESC LIMIT ? OFFSET ?`).all(...args,pageSize,(page-1)*pageSize) as any[];return res.json({data:rows.map(shape),total,page,page_size:pageSize,total_pages:Math.max(1,Math.ceil(total/pageSize))});});
router.get('/:id',(req,res)=>{const c=getComplaint(Number(req.params.id));if(!c)return fail(res,404,'Complaint not found');if(!allowed(req,c))return fail(res,403,'Forbidden');return ok(res,shape(c));});
router.put('/:id',(req,res)=>{const id=Number(req.params.id),c=getComplaint(id);if(!c)return fail(res,404,'Complaint not found');if(req.user!.role==='student'&&c.user_id!==req.user!.user_id)return fail(res,403,'Forbidden');const p=complaintUpdateSchema.safeParse(req.body);if(!p.success)return fail(res,400,'Invalid complaint payload');const d={...p.data};const t=nowIso();db.prepare(`UPDATE complaints SET title=?,description=?,category=?,location=?,updated_at=? WHERE id=?`).run(d.title??c.title,d.description??c.description,d.category??c.category,d.location??c.location,t,id);audit(req.user!.user_id,'UPDATE','complaints',id);return ok(res,shape(getComplaint(id)));});
router.delete('/:id',requireRole('admin'),(req,res)=>{const id=Number(req.params.id),r=db.prepare('DELETE FROM complaints WHERE id=?').run(id);if(!r.changes)return fail(res,404,'Complaint not found');audit(req.user!.user_id,'DELETE','complaints',id);return ok(res,{message:'Complaint deleted successfully'});});
router.put('/:id/assign',requireRole('admin','staff'),(req,res)=>{const id=Number(req.params.id),p=assignSchema.safeParse(req.body);if(!p.success)return fail(res,400,'department_id is required');const c=getComplaint(id);if(!c)return fail(res,404,'Complaint not found');if(!db.prepare('SELECT id FROM departments WHERE id=?').get(p.data.department_id))return fail(res,404,'Department not found');db.prepare('UPDATE complaints SET department_id=?,updated_at=? WHERE id=?').run(p.data.department_id,nowIso(),id);db.prepare('INSERT INTO complaint_updates(complaint_id,user_id,status,comment,updated_at) VALUES (?,?,?,?,?)').run(id,req.user!.user_id,c.status,`Assigned to department ${p.data.department_id}`,nowIso());audit(req.user!.user_id,'ASSIGN','complaints',id);return ok(res,shape(getComplaint(id)));});
router.put('/:id/status',requireRole('admin','staff'),(req,res)=>{const id=Number(req.params.id),p=statusSchema.safeParse(req.body);if(!p.success)return fail(res,400,'Invalid status');const c=getComplaint(id);if(!c)return fail(res,404,'Complaint not found');const transitions:any={pending:['in-progress','resolved','closed'],'in-progress':['resolved','closed','pending'],resolved:['closed'],closed:[]};if(!transitions[c.status]?.includes(p.data.status))return fail(res,400,`Cannot transition from '${c.status}' to '${p.data.status}'`);const t=nowIso();const resolved=p.data.status==='resolved'||p.data.status==='closed'?t:null;db.prepare('UPDATE complaints SET status=?,resolved_at=?,updated_at=? WHERE id=?').run(p.data.status,resolved,t,id);db.prepare('INSERT INTO complaint_updates(complaint_id,user_id,status,comment,updated_at) VALUES (?,?,?,?,?)').run(id,req.user!.user_id,p.data.status,`Status changed to ${p.data.status}`,t);audit(req.user!.user_id,'UPDATE_STATUS','complaints',id);return ok(res,shape(getComplaint(id)));});
router.post('/:id/comments',(req,res)=>{const id=Number(req.params.id),c=getComplaint(id);if(!c)return fail(res,404,'Complaint not found');if(!allowed(req,c))return fail(res,403,'Forbidden');const p=commentSchema.safeParse(req.body);if(!p.success)return fail(res,400,'Content is required');const t=nowIso();const r=db.prepare('INSERT INTO complaint_updates(complaint_id,user_id,status,comment,updated_at) VALUES (?,?,?,?,?)').run(id,req.user!.user_id,c.status,p.data.content,t);return ok(res,{id:Number(r.lastInsertRowid),complaint_id:id,user_id:req.user!.user_id,status:c.status,content:p.data.content,created_at:t});});
router.get('/:id/comments',(req,res)=>{const id=Number(req.params.id),c=getComplaint(id);if(!c)return fail(res,404,'Complaint not found');if(!allowed(req,c))return fail(res,403,'Forbidden');const rows=db.prepare(`SELECT cu.update_id id,cu.complaint_id,cu.user_id,u.name,u.username,u.email,u.role,cu.comment content,cu.updated_at created_at FROM complaint_updates cu JOIN users u ON u.id=cu.user_id WHERE cu.complaint_id=? AND cu.comment IS NOT NULL ORDER BY cu.updated_at ASC`).all(id) as any[];return ok(res,rows.map(r=>({...r,user:{id:r.user_id,name:r.name,username:r.username,email:r.email,role:r.role}})));});
router.post('/:id/attachments',upload.single('file'),(req,res)=>{const id=Number(req.params.id),c=getComplaint(id);if(!c)return fail(res,404,'Complaint not found');if(!allowed(req,c))return fail(res,403,'Forbidden');if(!req.file)return fail(res,400,'File is required');const t=nowIso();const r=db.prepare('INSERT INTO attachments(complaint_id,file_name,file_path,file_type,uploaded_at) VALUES (?,?,?,?,?)').run(id,req.file.originalname,req.file.path,req.file.mimetype,t);return ok(res,{attachment_id:Number(r.lastInsertRowid),complaint_id:id,file_name:req.file.originalname,file_path:req.file.path,file_type:req.file.mimetype,uploaded_at:t});});
router.get('/:id/attachments',(req,res)=>{const id=Number(req.params.id),c=getComplaint(id);if(!c)return fail(res,404,'Complaint not found');if(!allowed(req,c))return fail(res,403,'Forbidden');return ok(res,db.prepare('SELECT * FROM attachments WHERE complaint_id=? ORDER BY uploaded_at').all(id));});
router.post('/:id/feedback',(req,res)=>{const id=Number(req.params.id),c=getComplaint(id);if(!c)return fail(res,404,'Complaint not found');if(c.user_id!==req.user!.user_id)return fail(res,403,'Only the complaint owner can provide feedback');if(c.status!=='resolved')return fail(res,400,'Feedback is only available after resolution');const p=feedbackSchema.safeParse(req.body);if(!p.success)return fail(res,400,'Rating must be between 1 and 5');try{const t=nowIso();const r=db.prepare('INSERT INTO feedback(complaint_id,user_id,rating,comment,submitted_at) VALUES (?,?,?,?,?)').run(id,req.user!.user_id,p.data.rating,p.data.comment??null,t);return ok(res,{feedback_id:Number(r.lastInsertRowid),complaint_id:id,user_id:req.user!.user_id,rating:p.data.rating,comment:p.data.comment??null,submitted_at:t});}catch{return fail(res,409,'Feedback already submitted')}});
router.get('/:id/feedback',(req,res)=>{const id=Number(req.params.id),c=getComplaint(id);if(!c)return fail(res,404,'Complaint not found');if(!allowed(req,c)&&req.user!.role!=='admin')return fail(res,403,'Forbidden');return ok(res,db.prepare('SELECT * FROM feedback WHERE complaint_id=?').all(id));});
export async function reportRows(req:any){const cond:string[]=[];const args:any[]=[];if(req.user.role==='student'){cond.push('c.user_id=?');args.push(req.user.user_id)}if(req.query.from){cond.push('date(c.created_at)>=date(?)');args.push(String(req.query.from))}if(req.query.to){cond.push('date(c.created_at)<=date(?)');args.push(String(req.query.to))}const where=cond.length?' WHERE '+cond.join(' AND '):'';return db.prepare(`${select}${where} ORDER BY c.created_at DESC`).all(...args) as any[];}
export default router;
